[package]
name = "provenance-macros"
version.workspace = true
edition.workspace = true
description = "Supported Rule binding attributes and internal derives for Provenance"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
camino.workspace = true
provenance-scanner.workspace = true
trybuild.workspace = true
