-- Full-fidelity payload columns for the served read path.
ALTER TABLE sources ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE domains ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE requirements ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE boundaries ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE topics ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE questions ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE edges ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE resolutions ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE rules ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE threads ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE dispositions ADD COLUMN payload TEXT NOT NULL DEFAULT '';
