ALTER TABLE threads ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE proposal_cards ADD COLUMN payload TEXT NOT NULL DEFAULT '';
ALTER TABLE dispositions ADD COLUMN payload TEXT NOT NULL DEFAULT '';
