[package]
name = "provenance-store"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
fs2.workspace = true
provenance-core = { path = "../provenance-core" }
provenance-macros = { path = "../provenance-macros" }
provenance-scanner = { path = "../provenance-scanner" }
provenance-ste100 = { path = "../provenance-ste100" }
serde.workspace = true
serde_ignored.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
