import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { generatedDirectories, recordGeneration, generationIsCurrent } from './artifacts.mjs';

async function fixture(t) {
  const root = await mkdtemp(join(tmpdir(), 'provenance-generation-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await writeFile(join(root, 'Cargo.toml'), '[workspace]\nmembers = []\n');
  for (const path of generatedDirectories) {
    await mkdir(join(root, path), { recursive: true });
    await writeFile(join(root, path, 'output.txt'), 'generated bytes\n');
  }
  return root;
}

test('a recorded generation is reusable without Git or generator dependencies', async t => {
  const root = await fixture(t);
  assert.equal(await generationIsCurrent(root), false);
  await recordGeneration(root, root);
  assert.equal(await generationIsCurrent(root), true);
  // Windows checkout line endings must not invalidate a Linux build artifact.
  await writeFile(join(root, 'Cargo.toml'), '[workspace]\r\nmembers = []\r\n');
  assert.equal(await generationIsCurrent(root), true);
  await writeFile(join(root, 'Cargo.toml'), '[workspace]\nmembers = ["new"]\n');
  assert.equal(await generationIsCurrent(root), false);
});

test('missing, changed and stale output invalidate the generated build artifact', async t => {
  const root = await fixture(t);
  await recordGeneration(root, root);
  const output = join(root, generatedDirectories[1], 'output.txt');
  assert.equal(await generationIsCurrent(root), true);
  await writeFile(output, 'corrupt\n');
  assert.equal(await generationIsCurrent(root), false);
  await writeFile(output, 'generated bytes\n');
  const stale = join(root, generatedDirectories[1], 'old.ts');
  await writeFile(stale, 'stale');
  assert.equal(await generationIsCurrent(root), false);
  await rm(stale);
  await rm(output);
  assert.equal(await generationIsCurrent(root), false);
});

test('test and documentation edits do not invalidate generated source', async t => {
  const root = await fixture(t);
  await mkdir(join(root, 'tools/operation-codegen'), { recursive: true });
  await writeFile(join(root, 'tools/operation-codegen/templates.mjs'), 'export const version = 1;');
  await recordGeneration(root, root);
  await writeFile(join(root, 'tools/operation-codegen/README.md'), 'Documentation');
  await writeFile(join(root, 'tools/operation-codegen/example.test.mjs'), 'test code');
  assert.equal(await generationIsCurrent(root), true);
  await writeFile(join(root, 'tools/operation-codegen/templates.mjs'), 'export const version = 2;');
  assert.equal(await generationIsCurrent(root), false);
});
