#![allow(clippy::too_many_lines, clippy::wildcard_imports)]

use super::*;

pub(super) fn register(out: &mut Vec<Definition>) {
    resource!(
        out,
        provenance_core::Source,
        "sources",
        "source",
        "Source",
        "Sources",
        "create-source",
        "update-source"
    );
    let requirements = read::<provenance_core::Requirement>(
        "list-requirements",
        "listRequirements",
        "/requirements",
        "List requirements in the bound scope.",
        "list-requirements",
        ResponseKind::Items,
        list_parameters(true, false),
    );
    out.push(with_query_results(
        requirements,
        &[("search", ResponseKind::Items)],
    ));
    let requirement = backed(
        "get-requirement",
        "getRequirement",
        HttpMethod::Get,
        "/requirements/{id}",
        "Read one Requirement with its edit and decision state.",
        "get-requirement-v2",
        ResponseKind::Resource,
        &[],
        member_parameters(true),
    );
    out.push(with_query_results(
        requirement,
        &[
            ("trace", ResponseKind::Result),
            ("neighbors", ResponseKind::Result),
            ("impact", ResponseKind::Result),
        ],
    ));
    out.push(backed(
        "create-requirement",
        "createRequirement",
        HttpMethod::Post,
        "/requirements",
        "Create one Requirement through the guarded review journal.",
        "create-requirement-v2",
        ResponseKind::Resource,
        &["request_id"],
        Vec::new(),
    ));
    out.push(backed(
        "update-requirement",
        "updateRequirement",
        HttpMethod::Patch,
        "/requirements/{id}",
        "Apply one guarded Requirement text and relationship delta.",
        "update-requirement-v2",
        ResponseKind::Resource,
        &["request_id", "expected_etag", "id"],
        vec![schema::path("id")],
    ));
    resource!(
        out,
        provenance_core::Resolution,
        "resolutions",
        "resolution",
        "Resolution",
        "Resolutions",
        "create-resolution",
        "update-resolution"
    );
    resource!(
        out,
        provenance_core::Rule,
        "rules",
        "rule",
        "Rule",
        "Rules",
        "create-rule",
        "update-rule"
    );
    resource!(
        out,
        provenance_core::Domain,
        "domains",
        "domain",
        "Domain",
        "Domains",
        "create-domain",
        "update-domain"
    );
    resource!(
        out,
        provenance_core::Boundary,
        "boundaries",
        "boundary",
        "Boundary",
        "Boundaries",
        "create-boundary",
        "update-boundary"
    );
    resource!(
        out,
        provenance_core::Topic,
        "topics",
        "topic",
        "Topic",
        "Topics",
        "create-topic",
        "update-topic"
    );
    resource!(
        out,
        provenance_core::Question,
        "questions",
        "question",
        "Question",
        "Questions",
        "create-question",
        "update-question"
    );
    resource!(
        out,
        provenance_core::Contribution,
        "contributions",
        "contribution",
        "Contribution",
        "Contributions",
        "create-contribution",
        "upsert-contribution"
    );
    resource!(
        out,
        provenance_core::SynthesisPacket,
        "synthesis-packets",
        "synthesis-packet",
        "SynthesisPacket",
        "SynthesisPackets",
        "create-synthesis-packet",
        "upsert-synthesis-packet"
    );
    resource!(
        out,
        provenance_core::ProposalCard,
        "proposals",
        "proposal",
        "Proposal",
        "Proposals",
        "create-proposal",
        ""
    );
    resource!(
        out,
        provenance_core::VerificationRun,
        "verification-runs",
        "verification-run",
        "VerificationRun",
        "VerificationRuns",
        "",
        ""
    );
    resource!(
        out,
        provenance_core::VerificationBinding,
        "verification-bindings",
        "verification-binding",
        "VerificationBinding",
        "VerificationBindings",
        "",
        ""
    );
    indexes(out);
}

fn indexes(out: &mut Vec<Definition>) {
    resource!(
        out,
        provenance_core::Thread,
        "discussion-containers",
        "discussion-container",
        "DiscussionContainer",
        "DiscussionContainers",
        "",
        ""
    );
    resource!(
        out,
        provenance_core::Message,
        "messages",
        "message",
        "Message",
        "Messages",
        "",
        ""
    );
    resource!(
        out,
        provenance_core::AssertionRecord,
        "assertions",
        "assertion",
        "Assertion",
        "Assertions",
        "",
        ""
    );
    resource!(
        out,
        provenance_core::DispositionRecord,
        "dispositions",
        "disposition",
        "Disposition",
        "Dispositions",
        "",
        ""
    );
}
